/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaigns */
        get: operations["campaigns_api_v1_campaigns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign */
        get: operations["campaign_api_v1_campaigns__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{key}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Calendar */
        get: operations["campaign_calendar_api_v1_campaigns__key__calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{key}/offerings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Offerings */
        get: operations["campaign_offerings_api_v1_campaigns__key__offerings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/competition-pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Competition Pools */
        get: operations["competition_pools_api_v1_competition_pools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Gaps
         * @description List unresolved manual review items as recorded data gaps.
         */
        get: operations["data_gaps_api_v1_data_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Departments */
        get: operations["departments_api_v1_departments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Department */
        get: operations["department_api_v1_departments__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Directions */
        get: operations["directions_api_v1_directions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directions/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Direction */
        get: operations["direction_api_v1_directions__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exams */
        get: operations["exams_api_v1_exams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exam */
        get: operations["exam_api_v1_exams__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/individual-achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Individual Achievements */
        get: operations["individual_achievements_api_v1_individual_achievements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/place-quotas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Place Quotas */
        get: operations["place_quotas_api_v1_place_quotas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Programs */
        get: operations["programs_api_v1_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Program */
        get: operations["program_api_v1_programs__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{key}/study-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Program Study Plans */
        get: operations["program_study_plans_api_v1_programs__key__study_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release */
        get: operations["release_api_v1_release_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requirements */
        get: operations["requirements_api_v1_requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requirements/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requirement */
        get: operations["requirement_api_v1_requirements__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistics */
        get: operations["statistics_api_v1_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/study-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Study Plans */
        get: operations["study_plans_api_v1_study_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/study-plans/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Study Plan */
        get: operations["study_plan_api_v1_study_plans__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/study-plans/{key}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Study Plan Items */
        get: operations["study_plan_items_api_v1_study_plans__key__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subject-taxonomies/{taxonomy_key}/{taxonomy_version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subject Taxonomy */
        get: operations["subject_taxonomy_api_v1_subject_taxonomies__taxonomy_key___taxonomy_version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tuition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tuition */
        get: operations["tuition_api_v1_tuition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionCampaignRecord */
        AdmissionCampaignRecord: {
            /** Campaign Kind */
            campaign_kind: string;
            /** Campus Key */
            campus_key?: string | null;
            /**
             * Campus Status
             * @enum {string}
             */
            campus_status: "verified" | "unverified" | "not_stated";
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Date Note */
            date_note?: string | null;
            /** Education Level */
            education_level?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Title */
            title: string;
            /** University Key */
            university_key: string;
            /** Year */
            year: number;
        };
        /** AdmissionExamRecord */
        AdmissionExamRecord: {
            /** Code */
            code: string;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Name */
            name: string;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
        };
        /** AdmissionOfferingRecord */
        AdmissionOfferingRecord: {
            /** Campaign Key */
            campaign_key: string;
            /** Campus Scope */
            campus_scope?: string | null;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Department Code */
            department_code?: string | null;
            /** Department Key */
            department_key?: string | null;
            /** Direction Code */
            direction_code?: string | null;
            /** Direction Key */
            direction_key?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Language */
            language?: string | null;
            /** Places Total */
            places_total?: number | null;
            /** Program Key */
            program_key?: string | null;
            /**
             * Program Link Status
             * @enum {string}
             */
            program_link_status: "exact" | "unresolved" | "manual_review";
            /** Program Name In Source */
            program_name_in_source?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Study Duration Label */
            study_duration_label?: string | null;
            /** Study Form */
            study_form?: string | null;
        };
        /** CampaignCalendarEventRecord */
        CampaignCalendarEventRecord: {
            /** Campaign Key */
            campaign_key: string;
            /** Context */
            context?: string | null;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Date Text */
            date_text?: string | null;
            /** Date Value */
            date_value?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Event Code */
            event_code?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Label */
            label: string;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Starts At */
            starts_at?: string | null;
            /** Time Value */
            time_value?: string | null;
        };
        /** CompetitionPoolRecord */
        CompetitionPoolRecord: {
            /** Campaign Key */
            campaign_key: string;
            /** Campus Label In Document */
            campus_label_in_document?: string | null;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Department Code */
            department_code?: string | null;
            /** Department Key */
            department_key?: string | null;
            /**
             * Department Status
             * @enum {string}
             */
            department_status: "verified" | "unverified" | "unresolved" | "not_stated";
            /** Direction Code */
            direction_code?: string | null;
            /** Direction Key */
            direction_key?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Funding Type */
            funding_type?: string | null;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Observed At */
            observed_at?: string | null;
            /** Offering Key */
            offering_key?: string | null;
            /** Offering Keys */
            offering_keys?: string[];
            /** Places */
            places?: number | null;
            /** Places By Source Row */
            places_by_source_row?: {
                [key: string]: unknown;
            }[] | null;
            /** Quota Type */
            quota_type?: string | null;
            /** Scope Level */
            scope_level?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Target Organization */
            target_organization?: string | null;
            /** Target Organization Inn */
            target_organization_inn?: string | null;
            /** Target Organization Kpp */
            target_organization_kpp?: string | null;
            /** Target Organization Ogrn */
            target_organization_ogrn?: string | null;
            /** Target Region */
            target_region?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** CurriculumItemRecord */
        CurriculumItemRecord: {
            /** Chair Name */
            chair_name?: string | null;
            /** Control Form */
            control_form?: string | null;
            /** Credits */
            credits?: string | null;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Department Name */
            department_name?: string | null;
            /** Discipline Name */
            discipline_name?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Faculty Name */
            faculty_name?: string | null;
            /** Hours */
            hours?: number | null;
            /** Lab Hours */
            lab_hours?: number | null;
            /** Lecture Hours */
            lecture_hours?: number | null;
            /** Ordinal */
            ordinal: number;
            /** Practice Hours */
            practice_hours?: number | null;
            /** Self Study Hours */
            self_study_hours?: number | null;
            /** Semester */
            semester?: number | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Study Plan Key */
            study_plan_key: string;
            subject_classification?: components["schemas"]["SubjectClassificationSummary"] | null;
            /** Total Hours */
            total_hours?: number | null;
        };
        /** DataGap */
        DataGap: {
            /** Field Path */
            field_path: string;
            /** Reason */
            reason: string;
            /** Source Keys */
            source_keys?: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "not_stated" | "unavailable" | "unverified" | "unresolved" | "manual_review" | "conflict";
        };
        /** DepartmentRecord */
        DepartmentRecord: {
            /** Address */
            address?: string | null;
            /** Campus Key */
            campus_key?: string | null;
            /** Campus Scope */
            campus_scope?: string | null;
            /**
             * Campus Status
             * @enum {string}
             */
            campus_status: "verified" | "unverified" | "not_stated";
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Description */
            description?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Faculty Name */
            faculty_name?: string | null;
            /** Name */
            name: string;
            /** Official Code */
            official_code?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
        };
        /** DepartmentRelation */
        DepartmentRelation: {
            /** Department Key */
            department_key: string;
            /** Relation Type */
            relation_type?: string | null;
            /** Source Relation Type */
            source_relation_type?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "verified" | "unverified" | "manual_review";
        };
        /** DirectionRecord */
        DirectionRecord: {
            /** Code */
            code: string;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Degree Label */
            degree_label?: string | null;
            /** Department Keys */
            department_keys?: string[];
            /** Description */
            description?: string | null;
            /** Duration Label */
            duration_label?: string | null;
            /** Duration Months */
            duration_months?: number | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Name */
            name: string;
            /** Program Keys */
            program_keys?: string[];
            /** Qualification Label */
            qualification_label?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
        };
        /** EducationalProgramRecord */
        EducationalProgramRecord: {
            /** Campus Key */
            campus_key?: string | null;
            /** Campus Scope */
            campus_scope?: string | null;
            /**
             * Campus Status
             * @enum {string}
             */
            campus_status: "verified" | "unverified" | "not_stated";
            /** Catalog Course Names */
            catalog_course_names?: string[];
            /** Catalog Page Url */
            catalog_page_url?: string | null;
            /** Code */
            code: string;
            /** Course Keys */
            course_keys?: string[];
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Department Relations */
            department_relations?: components["schemas"]["DepartmentRelation"][];
            /** Description */
            description?: string | null;
            /** Direction Key */
            direction_key: string;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Name */
            name: string;
            /** Offering Keys */
            offering_keys?: string[];
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Study Plan Keys */
            study_plan_keys?: string[];
            /** Study Plan Url */
            study_plan_url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthRecord */
        HealthRecord: {
            /** Active Release Key */
            active_release_key: string;
            /**
             * Api Version
             * @constant
             */
            api_version: "v1";
            /**
             * Service
             * @constant
             */
            service: "andromeda-academic-data";
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /** IndividualAchievementRecord */
        IndividualAchievementRecord: {
            /** Campaign Key */
            campaign_key?: string | null;
            /** Code */
            code?: string | null;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Description */
            description?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Name */
            name: string;
            /** Observed At */
            observed_at?: string | null;
            /** Points */
            points?: string | null;
            /** Required Document */
            required_document?: string | null;
            /** Row Number */
            row_number?: number | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** ManualReviewRecord */
        ManualReviewRecord: {
            /** Candidate Keys */
            candidate_keys?: string[];
            /** External Key */
            external_key: string;
            /** Issue Type */
            issue_type: string;
            /** Reason */
            reason: string;
            /** Record Key */
            record_key: string;
            /** Source Key */
            source_key?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved" | "dismissed";
            /** Target Key */
            target_key?: string | null;
        };
        /** OfficialAdmissionStatisticRecord */
        OfficialAdmissionStatisticRecord: {
            /** Admission Stage */
            admission_stage?: string | null;
            /** Admitted Count */
            admitted_count?: number | null;
            /** Average Score */
            average_score?: string | null;
            /** Campaign Key */
            campaign_key?: string | null;
            /** Competition Type */
            competition_type?: string | null;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Direction Code */
            direction_code?: string | null;
            /** Direction Key */
            direction_key?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Funding Type */
            funding_type?: string | null;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Maximum Score */
            maximum_score?: string | null;
            /** Minimum Score */
            minimum_score?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Scope Label */
            scope_label?: string | null;
            /** Scope Type */
            scope_type?: string | null;
            /** Score */
            score?: string | null;
            /** Snapshot Date */
            snapshot_date?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Statistic Kind */
            statistic_kind?: string | null;
            /** Status */
            status?: string | null;
            /** Study Form */
            study_form?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Year */
            year: number;
        };
        /** PageResponse[AdmissionCampaignRecord] */
        PageResponse_AdmissionCampaignRecord_: {
            /** Items */
            items: components["schemas"]["AdmissionCampaignRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[AdmissionExamRecord] */
        PageResponse_AdmissionExamRecord_: {
            /** Items */
            items: components["schemas"]["AdmissionExamRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[AdmissionOfferingRecord] */
        PageResponse_AdmissionOfferingRecord_: {
            /** Items */
            items: components["schemas"]["AdmissionOfferingRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[CampaignCalendarEventRecord] */
        PageResponse_CampaignCalendarEventRecord_: {
            /** Items */
            items: components["schemas"]["CampaignCalendarEventRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[CompetitionPoolRecord] */
        PageResponse_CompetitionPoolRecord_: {
            /** Items */
            items: components["schemas"]["CompetitionPoolRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[CurriculumItemRecord] */
        PageResponse_CurriculumItemRecord_: {
            /** Items */
            items: components["schemas"]["CurriculumItemRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[DepartmentRecord] */
        PageResponse_DepartmentRecord_: {
            /** Items */
            items: components["schemas"]["DepartmentRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[DirectionRecord] */
        PageResponse_DirectionRecord_: {
            /** Items */
            items: components["schemas"]["DirectionRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[EducationalProgramRecord] */
        PageResponse_EducationalProgramRecord_: {
            /** Items */
            items: components["schemas"]["EducationalProgramRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[IndividualAchievementRecord] */
        PageResponse_IndividualAchievementRecord_: {
            /** Items */
            items: components["schemas"]["IndividualAchievementRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[ManualReviewRecord] */
        PageResponse_ManualReviewRecord_: {
            /** Items */
            items: components["schemas"]["ManualReviewRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[OfficialAdmissionStatisticRecord] */
        PageResponse_OfficialAdmissionStatisticRecord_: {
            /** Items */
            items: components["schemas"]["OfficialAdmissionStatisticRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[PlaceQuotaRecord] */
        PageResponse_PlaceQuotaRecord_: {
            /** Items */
            items: components["schemas"]["PlaceQuotaRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[RequirementTreeRecord] */
        PageResponse_RequirementTreeRecord_: {
            /** Items */
            items: components["schemas"]["RequirementTreeRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[StudyPlanRecord] */
        PageResponse_StudyPlanRecord_: {
            /** Items */
            items: components["schemas"]["StudyPlanRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PageResponse[TuitionRecord] */
        PageResponse_TuitionRecord_: {
            /** Items */
            items: components["schemas"]["TuitionRecord"][];
            page: components["schemas"]["PaginationMetadata"];
        };
        /** PaginationMetadata */
        PaginationMetadata: {
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Release Key */
            release_key: string;
            /** Total Count */
            total_count?: number | null;
        };
        /** PlaceQuotaRecord */
        PlaceQuotaRecord: {
            /** Campaign Key */
            campaign_key: string;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Funding Type */
            funding_type?: string | null;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Observed At */
            observed_at?: string | null;
            /** Places */
            places: number;
            /** Pool Key */
            pool_key?: string | null;
            /** Quota Type */
            quota_type?: string | null;
            /** Scope Level */
            scope_level?: string | null;
            /** Source Locators */
            source_locators?: {
                [key: string]: unknown;
            }[] | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** ReleaseMetadataRecord */
        ReleaseMetadataRecord: {
            /**
             * Activated At
             * Format: date-time
             */
            activated_at: string;
            /** Mapper Version */
            mapper_version: string;
            /**
             * Reconciliation Status
             * @enum {string}
             */
            reconciliation_status: "passed" | "passed_with_gaps";
            /** Release Key */
            release_key: string;
            /** Schema Revision */
            schema_revision: string;
            /** Source Bundle Sha256 */
            source_bundle_sha256: string;
        };
        /** RequirementLeaf */
        RequirementLeaf: {
            /** Is Choice */
            is_choice?: boolean | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "leaf";
            /** Minimum Score */
            minimum_score?: string | null;
            /** Node Key */
            node_key: string;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Subject Code */
            subject_code?: string | null;
            /** Subject Name */
            subject_name?: string | null;
            /** Tiebreak Rank */
            tiebreak_rank?: string | null;
        };
        /** RequirementOperatorNode */
        RequirementOperatorNode: {
            /** Children */
            children: (components["schemas"]["RequirementLeaf"] | components["schemas"]["RequirementOperatorNode"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "operator";
            /** Node Key */
            node_key: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "AND" | "OR" | "AT_LEAST";
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Threshold */
            threshold?: number | null;
        };
        /** RequirementTreeRecord */
        RequirementTreeRecord: {
            /** Applicant Category */
            applicant_category?: string | null;
            /** Campaign Key */
            campaign_key: string;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Direction Code */
            direction_code?: string | null;
            /** Direction Key */
            direction_key?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Observed At */
            observed_at?: string | null;
            /** Root */
            root: components["schemas"]["RequirementLeaf"] | components["schemas"]["RequirementOperatorNode"];
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** SourceEvidenceReference */
        SourceEvidenceReference: {
            /** Claim */
            claim?: string | null;
            /** Claim Path */
            claim_path: string;
            /** Evidence Key */
            evidence_key: string;
            /** Locator */
            locator?: {
                [key: string]: unknown;
            } | string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Source Artifact Key */
            source_artifact_key: string;
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "source_backed" | "unverified" | "manual_review";
        };
        /** SourceReference */
        SourceReference: {
            /** Fetched At */
            fetched_at?: string | null;
            /** Field Path */
            field_path?: string | null;
            /** Locator */
            locator?: {
                [key: string]: unknown;
            } | string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /** Source Artifact Key */
            source_artifact_key: string;
            /** Source Url */
            source_url?: string | null;
        };
        /** StudyPlanRecord */
        StudyPlanRecord: {
            /** Academic Year */
            academic_year?: string | null;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Document Url */
            document_url?: string | null;
            /** Download Url */
            download_url?: string | null;
            /** Duration Label */
            duration_label?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /** Header Profile Code */
            header_profile_code?: string | null;
            /** Item Count */
            item_count?: number | null;
            /** Profile Code */
            profile_code?: string | null;
            /**
             * Profile Link Status
             * @enum {string}
             */
            profile_link_status: "verified" | "unverified" | "unresolved" | "manual_review";
            /** Profile Name In Plan */
            profile_name_in_plan?: string | null;
            /** Program Key */
            program_key?: string | null;
            /** Semester Count */
            semester_count?: number | null;
            /** Semester Totals */
            semester_totals?: {
                [key: string]: unknown;
            }[] | null;
            /** Source Version */
            source_version?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /**
             * Status
             * @enum {string}
             */
            status: "parsed" | "unavailable" | "unverified";
            /** Study Form */
            study_form?: string | null;
            /** Study Plan Url */
            study_plan_url?: string | null;
            /** Total Academic Hours */
            total_academic_hours?: number | null;
            /** Total Astronomical Hours */
            total_astronomical_hours?: number | null;
            /** Unavailable Reason */
            unavailable_reason?: string | null;
            /** Version Label */
            version_label?: string | null;
        };
        /** SubjectClassificationSummary */
        SubjectClassificationSummary: {
            /** Category Code */
            category_code: string;
            /** Category Name */
            category_name: string;
            /** Confidence */
            confidence: number;
            /** Model */
            model: string;
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Review Reasons */
            review_reasons?: string[];
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "classified" | "needs_review";
            /** Run Key */
            run_key: string;
            /** Taxonomy Key */
            taxonomy_key: string;
            /** Taxonomy Version */
            taxonomy_version: string;
        };
        /** SubjectTaxonomyCategoryRecord */
        SubjectTaxonomyCategoryRecord: {
            /** Category Code */
            category_code: string;
            /** Definition */
            definition: string;
            /** Name */
            name: string;
            /** Ordinal */
            ordinal: number;
        };
        /** SubjectTaxonomyRecord */
        SubjectTaxonomyRecord: {
            /** Categories */
            categories: components["schemas"]["SubjectTaxonomyCategoryRecord"][];
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Taxonomy Key */
            taxonomy_key: string;
            /** Taxonomy Version */
            taxonomy_version: string;
        };
        /** TuitionRecord */
        TuitionRecord: {
            /** Academic Year */
            academic_year?: string | null;
            /** Amount */
            amount?: string | null;
            /** Campaign Key */
            campaign_key?: string | null;
            /** Campus Scope */
            campus_scope?: string | null;
            /** Currency */
            currency?: string | null;
            /** Data Gaps */
            data_gaps?: components["schemas"]["DataGap"][];
            /** Direction Code */
            direction_code?: string | null;
            /** Direction Key */
            direction_key?: string | null;
            /** Direction Name */
            direction_name?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["SourceEvidenceReference"][];
            /** External Key */
            external_key: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Observed At */
            observed_at?: string | null;
            /** Program Key */
            program_key?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceReference"][];
            /** Table Category */
            table_category?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    campaigns_api_v1_campaigns_get: {
        parameters: {
            query?: {
                year?: number | null;
                education_level?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_AdmissionCampaignRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_api_v1_campaigns__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionCampaignRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_calendar_api_v1_campaigns__key__calendar_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_CampaignCalendarEventRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_offerings_api_v1_campaigns__key__offerings_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_AdmissionOfferingRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    competition_pools_api_v1_competition_pools_get: {
        parameters: {
            query?: {
                campaign_key?: string | null;
                direction_code?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_CompetitionPoolRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_gaps_api_v1_data_gaps_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_ManualReviewRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    departments_api_v1_departments_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_DepartmentRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    department_api_v1_departments__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    directions_api_v1_directions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_DirectionRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    direction_api_v1_directions__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exams_api_v1_exams_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_AdmissionExamRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exam_api_v1_exams__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionExamRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRecord"];
                };
            };
        };
    };
    individual_achievements_api_v1_individual_achievements_get: {
        parameters: {
            query?: {
                campaign_key?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_IndividualAchievementRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_quotas_api_v1_place_quotas_get: {
        parameters: {
            query?: {
                campaign_key?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_PlaceQuotaRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    programs_api_v1_programs_get: {
        parameters: {
            query?: {
                direction_key?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_EducationalProgramRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    program_api_v1_programs__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EducationalProgramRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    program_study_plans_api_v1_programs__key__study_plans_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_StudyPlanRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_api_v1_release_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseMetadataRecord"];
                };
            };
        };
    };
    requirements_api_v1_requirements_get: {
        parameters: {
            query?: {
                campaign_key?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_RequirementTreeRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requirement_api_v1_requirements__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementTreeRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_api_v1_statistics_get: {
        parameters: {
            query?: {
                kind?: "historical" | "admission";
                year?: number | null;
                direction_code?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_OfficialAdmissionStatisticRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    study_plans_api_v1_study_plans_get: {
        parameters: {
            query?: {
                program_key?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_StudyPlanRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    study_plan_api_v1_study_plans__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyPlanRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    study_plan_items_api_v1_study_plans__key__items_get: {
        parameters: {
            query?: {
                semester?: number | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_CurriculumItemRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subject_taxonomy_api_v1_subject_taxonomies__taxonomy_key___taxonomy_version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomy_key: string;
                taxonomy_version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectTaxonomyRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tuition_api_v1_tuition_get: {
        parameters: {
            query?: {
                direction_code?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_TuitionRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
