"""add academic data records

Revision ID: e0784a907d45
Revises: 0001_initial_service_metadata
Create Date: 2026-10-03 00:58:38.573868
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e0784a907d45"
down_revision: str | None = "0001_initial_service_metadata"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admission_documents",
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("document_group", sa.Text(), nullable=True),
        sa.Column("scope_tag", sa.String(length=120), nullable=True),
        sa.Column("captured", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_documents_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_documents")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_documents_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_documents_release_id"),
    )
    op.create_index(
        "ix_admission_documents_release_scope",
        "admission_documents",
        ["release_id", "scope_tag"],
        unique=False,
    )
    op.create_table(
        "admission_exams",
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_exams_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_exams")),
        sa.UniqueConstraint("release_id", "code", name="uq_admission_exams_release_code"),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_exams_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_exams_release_id"),
    )
    op.create_table(
        "admission_result_sources",
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("classification", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("stored", sa.Boolean(), nullable=False),
        sa.Column("omission_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_admission_result_sources_valid_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_result_sources_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_result_sources")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_result_sources_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_result_sources_release_id"),
    )
    op.create_index(
        "ix_admission_result_sources_release_stored",
        "admission_result_sources",
        ["release_id", "stored"],
        unique=False,
    )
    op.create_table(
        "funding_types",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_funding_types_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funding_types")),
        sa.UniqueConstraint("release_id", "code", name="uq_funding_types_release_code"),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_funding_types_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_funding_types_release_id"),
    )
    op.create_table(
        "quota_types",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_quota_types_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_types")),
        sa.UniqueConstraint("release_id", "code", name="uq_quota_types_release_code"),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_quota_types_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_quota_types_release_id"),
    )
    op.create_table(
        "source_artifacts",
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column("requested_url", sa.Text(), nullable=True),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("content_type", sa.String(length=160), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("raw_path", sa.Text(), nullable=True),
        sa.Column("storage_status", sa.String(length=48), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_artifacts_valid_sha256"),
        ),
        sa.CheckConstraint(
            "byte_size IS NULL OR byte_size >= 0",
            name=op.f("ck_source_artifacts_nonnegative_byte_size"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_source_artifacts_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_artifacts")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_source_artifacts_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_source_artifacts_release_id"),
    )
    op.create_index(
        "ix_source_artifacts_release_storage_status",
        "source_artifacts",
        ["release_id", "storage_status"],
        unique=False,
    )
    op.create_table(
        "universities",
        sa.Column("official_code", sa.String(length=80), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("official_site", sa.Text(), nullable=True),
        sa.Column("identity_source_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_universities_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universities")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_universities_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_universities_release_id"),
        sa.UniqueConstraint("release_id", "official_code", name="uq_universities_release_code"),
    )
    op.create_table(
        "admission_campaigns",
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("education_level", sa.String(length=80), nullable=True),
        sa.Column("campaign_kind", sa.String(length=80), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("date_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "year BETWEEN 1900 AND 2200", name=op.f("ck_admission_campaigns_valid_year")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "university_id"],
            ["universities.release_id", "universities.id"],
            name="fk_admission_campaigns_university_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_campaigns_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_campaigns")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_campaigns_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_campaigns_release_id"),
        sa.UniqueConstraint(
            "release_id", "university_id", "year", "campaign_kind", name="uq_campaign_identity"
        ),
    )
    op.create_index(
        "ix_admission_campaigns_release_year",
        "admission_campaigns",
        ["release_id", "year"],
        unique=False,
    )
    op.create_table(
        "admission_document_pages",
        sa.Column("document_id_fk", sa.Uuid(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("page_text", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "page_number >= 1", name=op.f("ck_admission_document_pages_valid_page_number")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "document_id_fk"],
            ["admission_documents.release_id", "admission_documents.id"],
            name="fk_admission_document_pages_document_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_document_pages_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_document_pages")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_document_pages_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_document_pages_release_id"),
    )
    op.create_index(
        "ix_admission_document_pages_release_document",
        "admission_document_pages",
        ["release_id", "document_id_fk"],
        unique=False,
    )
    op.create_table(
        "departments",
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("official_code", sa.String(length=80), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("faculty_name", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("campus_scope", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "university_id"],
            ["universities.release_id", "universities.id"],
            name="fk_departments_university_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_departments_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_departments_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_departments_release_id"),
        sa.UniqueConstraint(
            "release_id", "university_id", "official_code", name="uq_departments_university_code"
        ),
    )
    op.create_index(
        "ix_departments_release_code", "departments", ["release_id", "official_code"], unique=False
    )
    op.create_table(
        "directions",
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("degree_label", sa.String(length=200), nullable=True),
        sa.Column("duration_label", sa.String(length=100), nullable=True),
        sa.Column("duration_months", sa.Integer(), nullable=True),
        sa.Column("qualification_label", sa.String(length=200), nullable=True),
        sa.Column("catalog_course_names", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("catalog_page_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "duration_months IS NULL OR duration_months > 0",
            name=op.f("ck_directions_valid_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "university_id"],
            ["universities.release_id", "universities.id"],
            name="fk_directions_university_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_directions_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directions")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_directions_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_directions_release_id"),
        sa.UniqueConstraint(
            "release_id", "university_id", "code", name="uq_directions_university_code"
        ),
    )
    op.create_index(
        "ix_directions_release_code", "directions", ["release_id", "code"], unique=False
    )
    op.create_table(
        "manual_review_items",
        sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column("issue_code", sa.String(length=100), nullable=False),
        sa.Column("subject_type", sa.String(length=100), nullable=True),
        sa.Column("subject_key", sa.String(length=512), nullable=True),
        sa.Column("source_key", sa.String(length=512), nullable=True),
        sa.Column("target_key", sa.String(length=512), nullable=True),
        sa.Column("candidate_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'resolved', 'dismissed')",
            name=op.f("ck_manual_review_items_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "source_artifact_id"],
            ["source_artifacts.release_id", "source_artifacts.id"],
            name="fk_manual_review_items_artifact_release",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_manual_review_items_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_review_items")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_manual_review_items_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_manual_review_items_release_id"),
    )
    op.create_index(
        "ix_manual_review_items_release_status",
        "manual_review_items",
        ["release_id", "status"],
        unique=False,
    )
    op.create_table(
        "source_observations",
        sa.Column("dataset_name", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "source_artifact_id"],
            ["source_artifacts.release_id", "source_artifacts.id"],
            name="fk_source_observations_artifact_release",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_source_observations_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_observations")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_source_observations_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_source_observations_release_id"),
    )
    op.create_index(
        "ix_source_observations_release_dataset",
        "source_observations",
        ["release_id", "dataset_name"],
        unique=False,
    )
    op.create_table(
        "source_relationships",
        sa.Column("relation_type", sa.String(length=100), nullable=False),
        sa.Column("source_key", sa.String(length=512), nullable=False),
        sa.Column("target_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_kind", sa.String(length=100), nullable=True),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "length(source_key) > 0", name=op.f("ck_source_relationships_source_key_present")
        ),
        sa.CheckConstraint(
            "length(target_key) > 0", name=op.f("ck_source_relationships_target_key_present")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "source_artifact_id"],
            ["source_artifacts.release_id", "source_artifacts.id"],
            name="fk_source_relationships_artifact_release",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_source_relationships_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_relationships")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_source_relationships_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_source_relationships_release_id"),
    )
    op.create_index(
        "ix_source_relationships_release_type",
        "source_relationships",
        ["release_id", "relation_type"],
        unique=False,
    )
    op.create_table(
        "admission_requirement_sets",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("direction_id", sa.Uuid(), nullable=True),
        sa.Column("applicant_category_text", sa.Text(), nullable=True),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_requirement_tree", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "campaign_id"],
            ["admission_campaigns.release_id", "admission_campaigns.id"],
            name="fk_requirement_sets_campaign_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_requirement_sets_direction_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_requirement_sets_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_requirement_sets")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_requirement_sets_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_requirement_sets_release_id"),
    )
    op.create_index(
        "ix_requirement_sets_release_campaign",
        "admission_requirement_sets",
        ["release_id", "campaign_id"],
        unique=False,
    )
    op.create_table(
        "admission_statistics",
        sa.Column("direction_id", sa.Uuid(), nullable=True),
        sa.Column("funding_type_id", sa.Uuid(), nullable=True),
        sa.Column("admission_year", sa.Integer(), nullable=False),
        sa.Column("admission_stage", sa.String(length=80), nullable=True),
        sa.Column("competition_type", sa.String(length=100), nullable=True),
        sa.Column("funding_type_code", sa.String(length=100), nullable=True),
        sa.Column("score", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("study_form", sa.String(length=80), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "admission_year BETWEEN 1900 AND 2200",
            name=op.f("ck_admission_statistics_valid_admission_year"),
        ),
        sa.CheckConstraint(
            "score IS NULL OR score >= 0", name=op.f("ck_admission_statistics_nonnegative_score")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_admission_statistics_direction_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "funding_type_id"],
            ["funding_types.release_id", "funding_types.id"],
            name="fk_admission_statistics_funding_type_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_statistics_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_statistics")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_statistics_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_statistics_release_id"),
    )
    op.create_index(
        "ix_admission_statistics_release_year",
        "admission_statistics",
        ["release_id", "admission_year"],
        unique=False,
    )
    op.create_table(
        "campaign_calendar_events",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("event_code", sa.String(length=120), nullable=True),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("date_value", sa.Date(), nullable=True),
        sa.Column("time_value", sa.Time(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_text", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "starts_at IS NULL OR ends_at IS NULL OR starts_at <= ends_at",
            name=op.f("ck_campaign_calendar_events_valid_time_range"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "campaign_id"],
            ["admission_campaigns.release_id", "admission_campaigns.id"],
            name="fk_campaign_calendar_events_campaign_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_campaign_calendar_events_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_calendar_events")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_campaign_calendar_events_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_campaign_calendar_events_release_id"),
    )
    op.create_index(
        "ix_campaign_calendar_events_release_campaign",
        "campaign_calendar_events",
        ["release_id", "campaign_id"],
        unique=False,
    )
    op.create_table(
        "competition_pools",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("direction_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("funding_type_id", sa.Uuid(), nullable=True),
        sa.Column("quota_type_id", sa.Uuid(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("funding_type_code", sa.String(length=100), nullable=True),
        sa.Column("quota_type_code", sa.String(length=100), nullable=True),
        sa.Column("scope_level", sa.String(length=80), nullable=True),
        sa.Column("places", sa.Integer(), nullable=True),
        sa.Column("places_by_source_row", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_locators", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "places IS NULL OR places >= 0", name=op.f("ck_competition_pools_nonnegative_places")
        ),
        sa.CheckConstraint(
            "year BETWEEN 1900 AND 2200", name=op.f("ck_competition_pools_valid_year")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "campaign_id"],
            ["admission_campaigns.release_id", "admission_campaigns.id"],
            name="fk_competition_pools_campaign_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "department_id"],
            ["departments.release_id", "departments.id"],
            name="fk_competition_pools_department_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_competition_pools_direction_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "funding_type_id"],
            ["funding_types.release_id", "funding_types.id"],
            name="fk_competition_pools_funding_type_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "quota_type_id"],
            ["quota_types.release_id", "quota_types.id"],
            name="fk_competition_pools_quota_type_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_competition_pools_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_pools")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_competition_pools_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_competition_pools_release_id"),
    )
    op.create_index(
        "ix_competition_pools_release_campaign",
        "competition_pools",
        ["release_id", "campaign_id"],
        unique=False,
    )
    op.create_index(
        "ix_competition_pools_release_direction",
        "competition_pools",
        ["release_id", "direction_id"],
        unique=False,
    )
    op.create_table(
        "direction_departments",
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=32), nullable=True),
        sa.Column("source_relation_type", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "department_id"],
            ["departments.release_id", "departments.id"],
            name="fk_direction_departments_department_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_direction_departments_direction_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_direction_departments_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_direction_departments")),
        sa.UniqueConstraint(
            "release_id", "direction_id", "department_id", name="uq_direction_departments_pair"
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_direction_departments_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_direction_departments_release_id"),
    )
    op.create_table(
        "educational_programs",
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("source_code", sa.String(length=100), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("campus_scope", sa.String(length=100), nullable=True),
        sa.Column("catalog_course_names", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("catalog_page_url", sa.Text(), nullable=True),
        sa.Column("study_plan_url", sa.Text(), nullable=True),
        sa.Column("source_card_position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "campus_scope IS NULL OR campus_scope IN ('head_moscow', 'other', 'unknown')",
            name=op.f("ck_educational_programs_valid_campus_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_educational_programs_direction_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_educational_programs_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_educational_programs")),
        sa.UniqueConstraint(
            "release_id", "direction_id", "code", name="uq_programs_direction_code"
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_educational_programs_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_educational_programs_release_id"),
    )
    op.create_index(
        "ix_educational_programs_release_code",
        "educational_programs",
        ["release_id", "code"],
        unique=False,
    )
    op.create_table(
        "historical_admission_statistics",
        sa.Column("direction_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("funding_type_id", sa.Uuid(), nullable=True),
        sa.Column("admission_year", sa.Integer(), nullable=False),
        sa.Column("outcome_type", sa.String(length=100), nullable=False),
        sa.Column("scope_type", sa.String(length=80), nullable=True),
        sa.Column("scope_label", sa.String(length=160), nullable=True),
        sa.Column("funding_type_code", sa.String(length=100), nullable=True),
        sa.Column("study_form", sa.String(length=80), nullable=True),
        sa.Column("admitted_count", sa.Integer(), nullable=True),
        sa.Column("minimum_score", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("maximum_score", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("average_score", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("campus_scope", sa.String(length=120), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=True),
        sa.Column("finality_note", sa.Text(), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "admission_year BETWEEN 1900 AND 2200",
            name=op.f("ck_historical_admission_statistics_valid_admission_year"),
        ),
        sa.CheckConstraint(
            "admitted_count IS NULL OR admitted_count >= 0",
            name=op.f("ck_historical_admission_statistics_nonnegative_admitted_count"),
        ),
        sa.CheckConstraint(
            "average_score IS NULL OR average_score >= 0",
            name=op.f("ck_historical_admission_statistics_nonnegative_average_score"),
        ),
        sa.CheckConstraint(
            "maximum_score IS NULL OR maximum_score >= 0",
            name=op.f("ck_historical_admission_statistics_nonnegative_maximum_score"),
        ),
        sa.CheckConstraint(
            "minimum_score IS NULL OR minimum_score >= 0",
            name=op.f("ck_historical_admission_statistics_nonnegative_minimum_score"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "department_id"],
            ["departments.release_id", "departments.id"],
            name="fk_historical_statistics_department_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_historical_statistics_direction_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "funding_type_id"],
            ["funding_types.release_id", "funding_types.id"],
            name="fk_historical_statistics_funding_type_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_historical_admission_statistics_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_admission_statistics")),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_historical_admission_statistics_release_external_key",
        ),
        sa.UniqueConstraint(
            "release_id", "id", name="uq_historical_admission_statistics_release_id"
        ),
    )
    op.create_index(
        "ix_historical_statistics_release_year",
        "historical_admission_statistics",
        ["release_id", "admission_year"],
        unique=False,
    )
    op.create_table(
        "individual_achievement_policies",
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_year", sa.Integer(), nullable=True),
        sa.Column("achievement_name", sa.Text(), nullable=False),
        sa.Column("additional_points", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("required_document", sa.Text(), nullable=True),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "additional_points IS NULL OR additional_points >= 0",
            name=op.f("ck_individual_achievement_policies_nonnegative_additional_points"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "campaign_id"],
            ["admission_campaigns.release_id", "admission_campaigns.id"],
            name="fk_achievement_policies_campaign_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_individual_achievement_policies_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_individual_achievement_policies")),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_individual_achievement_policies_release_external_key",
        ),
        sa.UniqueConstraint(
            "release_id", "id", name="uq_individual_achievement_policies_release_id"
        ),
    )
    op.create_index(
        "ix_achievement_policies_release_campaign",
        "individual_achievement_policies",
        ["release_id", "campaign_id"],
        unique=False,
    )
    op.create_table(
        "tuition_assertions",
        sa.Column("direction_id", sa.Uuid(), nullable=True),
        sa.Column("direction_code", sa.String(length=32), nullable=True),
        sa.Column("direction_name", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("academic_year_label", sa.String(length=80), nullable=True),
        sa.Column("table_category", sa.String(length=120), nullable=True),
        sa.Column("campus_scope", sa.String(length=120), nullable=True),
        sa.Column("raw_cells", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "amount IS NULL OR amount >= 0", name=op.f("ck_tuition_assertions_nonnegative_amount")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_tuition_assertions_direction_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_tuition_assertions_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tuition_assertions")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_tuition_assertions_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_tuition_assertions_release_id"),
    )
    op.create_index(
        "ix_tuition_assertions_release_direction",
        "tuition_assertions",
        ["release_id", "direction_id"],
        unique=False,
    )
    op.create_table(
        "admission_requirement_nodes",
        sa.Column("requirement_set_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("path_key", sa.String(length=512), nullable=False),
        sa.Column("node_kind", sa.String(length=16), nullable=False),
        sa.Column("operator", sa.String(length=16), nullable=True),
        sa.Column("min_count", sa.Integer(), nullable=True),
        sa.Column("exam_id", sa.Uuid(), nullable=True),
        sa.Column("subject_code", sa.String(length=120), nullable=True),
        sa.Column("minimum_score", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("is_choice", sa.Boolean(), nullable=True),
        sa.Column("tiebreak_rank", sa.String(length=24), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "(node_kind = 'operator' AND operator IS NOT NULL AND exam_id IS NULL "
            "AND minimum_score IS NULL) OR (node_kind = 'exam' AND operator IS NULL "
            "AND exam_id IS NOT NULL AND min_count IS NULL)",
            name=op.f("ck_admission_requirement_nodes_node_shape_matches_kind"),
        ),
        sa.CheckConstraint(
            "node_kind IN ('operator', 'exam')",
            name=op.f("ck_admission_requirement_nodes_valid_node_kind"),
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id",
            name=op.f("ck_admission_requirement_nodes_parent_not_self"),
        ),
        sa.CheckConstraint(
            "operator IS NULL OR operator IN ('AND', 'OR', 'AT_LEAST')",
            name=op.f("ck_admission_requirement_nodes_valid_operator"),
        ),
        sa.CheckConstraint(
            "min_count IS NULL OR min_count >= 1",
            name=op.f("ck_admission_requirement_nodes_valid_min_count"),
        ),
        sa.CheckConstraint(
            "minimum_score IS NULL OR minimum_score >= 0",
            name=op.f("ck_admission_requirement_nodes_nonnegative_minimum_score"),
        ),
        sa.CheckConstraint(
            "ordinal >= 0", name=op.f("ck_admission_requirement_nodes_valid_ordinal")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "exam_id"],
            ["admission_exams.release_id", "admission_exams.id"],
            name="fk_requirement_nodes_exam_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "requirement_set_id", "parent_id"],
            [
                "admission_requirement_nodes.release_id",
                "admission_requirement_nodes.requirement_set_id",
                "admission_requirement_nodes.id",
            ],
            name="fk_requirement_nodes_parent_same_tree",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "requirement_set_id"],
            ["admission_requirement_sets.release_id", "admission_requirement_sets.id"],
            name="fk_requirement_nodes_set_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_requirement_nodes_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_requirement_nodes")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_requirement_nodes_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_requirement_nodes_release_id"),
        sa.UniqueConstraint(
            "release_id", "requirement_set_id", "id", name="uq_requirement_nodes_set_id"
        ),
        sa.UniqueConstraint(
            "release_id", "requirement_set_id", "path_key", name="uq_requirement_nodes_set_path"
        ),
        sa.UniqueConstraint(
            "release_id",
            "requirement_set_id",
            "parent_id",
            "ordinal",
            name="uq_requirement_nodes_sibling_order",
        ),
    )
    op.create_index(
        "ix_requirement_nodes_release_set_parent",
        "admission_requirement_nodes",
        ["release_id", "requirement_set_id", "parent_id"],
        unique=False,
    )
    op.create_index(
        "uq_requirement_nodes_single_root",
        "admission_requirement_nodes",
        ["release_id", "requirement_set_id"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_table(
        "catalog_courses",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_status", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "program_id"],
            ["educational_programs.release_id", "educational_programs.id"],
            name="fk_catalog_courses_program_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_catalog_courses_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_courses")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_catalog_courses_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_catalog_courses_release_id"),
    )
    op.create_index(
        "ix_catalog_courses_release_program",
        "catalog_courses",
        ["release_id", "program_id"],
        unique=False,
    )
    op.create_table(
        "educational_program_departments",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=32), nullable=True),
        sa.Column("verification_status", sa.String(length=24), nullable=False),
        sa.Column("source_relation_type", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "relation_type IS NULL OR relation_type IN ('owner', 'coordinator', 'teaching')",
            name=op.f("ck_educational_program_departments_valid_relation_type"),
        ),
        sa.CheckConstraint(
            "verification_status IN ('verified', 'unverified', 'manual_review')",
            name=op.f("ck_educational_program_departments_valid_verification_status"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "department_id"],
            ["departments.release_id", "departments.id"],
            name="fk_program_departments_department_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "program_id"],
            ["educational_programs.release_id", "educational_programs.id"],
            name="fk_program_departments_program_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_educational_program_departments_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_educational_program_departments")),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_educational_program_departments_release_external_key",
        ),
        sa.UniqueConstraint(
            "release_id", "id", name="uq_educational_program_departments_release_id"
        ),
        sa.UniqueConstraint(
            "release_id", "program_id", "department_id", name="uq_program_departments_pair"
        ),
    )
    op.create_table(
        "program_offerings",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("direction_id", sa.Uuid(), nullable=True),
        sa.Column("program_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("study_form", sa.String(length=80), nullable=True),
        sa.Column("language", sa.String(length=80), nullable=True),
        sa.Column("study_duration_label", sa.String(length=100), nullable=True),
        sa.Column("program_name_in_document", sa.Text(), nullable=True),
        sa.Column("campus_scope", sa.String(length=100), nullable=True),
        sa.Column("catalog_join_status", sa.String(length=100), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_row", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "year BETWEEN 1900 AND 2200", name=op.f("ck_program_offerings_valid_year")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "campaign_id"],
            ["admission_campaigns.release_id", "admission_campaigns.id"],
            name="fk_program_offerings_campaign_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "department_id"],
            ["departments.release_id", "departments.id"],
            name="fk_program_offerings_department_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_program_offerings_direction_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "program_id"],
            ["educational_programs.release_id", "educational_programs.id"],
            name="fk_program_offerings_program_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_program_offerings_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_offerings")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_program_offerings_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_program_offerings_release_id"),
    )
    op.create_index(
        "ix_program_offerings_release_campaign",
        "program_offerings",
        ["release_id", "campaign_id"],
        unique=False,
    )
    op.create_index(
        "ix_program_offerings_release_direction",
        "program_offerings",
        ["release_id", "direction_id"],
        unique=False,
    )
    op.create_table(
        "study_plans",
        sa.Column("program_id", sa.Uuid(), nullable=True),
        sa.Column("profile_link_status", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("education_year", sa.Integer(), nullable=True),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("version_label", sa.String(length=160), nullable=True),
        sa.Column("source_version", sa.String(length=160), nullable=True),
        sa.Column("profile_code", sa.String(length=100), nullable=True),
        sa.Column("header_profile_code", sa.String(length=100), nullable=True),
        sa.Column("profile_name_in_plan", sa.Text(), nullable=True),
        sa.Column("study_form", sa.String(length=80), nullable=True),
        sa.Column("duration_label", sa.String(length=100), nullable=True),
        sa.Column("semester_count", sa.Integer(), nullable=True),
        sa.Column("total_academic_hours", sa.Integer(), nullable=True),
        sa.Column("total_astronomical_hours", sa.Integer(), nullable=True),
        sa.Column("semester_totals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("document_url", sa.Text(), nullable=True),
        sa.Column("download_url", sa.Text(), nullable=True),
        sa.Column("study_plan_url", sa.Text(), nullable=True),
        sa.Column("unavailable_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "profile_link_status IN ('verified', 'unverified', 'unresolved', 'manual_review')",
            name=op.f("ck_study_plans_valid_profile_link_status"),
        ),
        sa.CheckConstraint(
            "education_year IS NULL OR education_year >= 1900",
            name=op.f("ck_study_plans_valid_education_year"),
        ),
        sa.CheckConstraint(
            "semester_count IS NULL OR semester_count >= 0",
            name=op.f("ck_study_plans_valid_semester_count"),
        ),
        sa.CheckConstraint(
            "status IN ('parsed', 'unavailable', 'unverified')",
            name=op.f("ck_study_plans_valid_status"),
        ),
        sa.CheckConstraint(
            "total_academic_hours IS NULL OR total_academic_hours >= 0",
            name=op.f("ck_study_plans_nonnegative_total_academic_hours"),
        ),
        sa.CheckConstraint(
            "total_astronomical_hours IS NULL OR total_astronomical_hours >= 0",
            name=op.f("ck_study_plans_nonnegative_total_astronomical_hours"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "program_id"],
            ["educational_programs.release_id", "educational_programs.id"],
            name="fk_study_plans_program_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_study_plans_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_plans")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_study_plans_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_study_plans_release_id"),
    )
    op.create_index(
        "ix_study_plans_release_program", "study_plans", ["release_id", "program_id"], unique=False
    )
    op.create_table(
        "competition_pool_offerings",
        sa.Column("pool_id", sa.Uuid(), nullable=False),
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "offering_id"],
            ["program_offerings.release_id", "program_offerings.id"],
            name="fk_pool_offerings_offering_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "pool_id"],
            ["competition_pools.release_id", "competition_pools.id"],
            name="fk_pool_offerings_pool_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_competition_pool_offerings_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_pool_offerings")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_competition_pool_offerings_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_competition_pool_offerings_release_id"),
        sa.UniqueConstraint("release_id", "pool_id", "offering_id", name="uq_pool_offerings_pair"),
    )
    op.create_table(
        "curriculum_items",
        sa.Column("study_plan_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("record_type", sa.String(length=80), nullable=True),
        sa.Column("is_data_row", sa.Boolean(), nullable=True),
        sa.Column("source_record_id", sa.String(length=120), nullable=True),
        sa.Column("discipline_name", sa.Text(), nullable=True),
        sa.Column("course_number", sa.Integer(), nullable=True),
        sa.Column("semester", sa.Integer(), nullable=True),
        sa.Column("credits", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("hours", sa.Integer(), nullable=True),
        sa.Column("lecture_hours", sa.Integer(), nullable=True),
        sa.Column("practice_hours", sa.Integer(), nullable=True),
        sa.Column("lab_hours", sa.Integer(), nullable=True),
        sa.Column("self_study_hours", sa.Integer(), nullable=True),
        sa.Column("total_hours", sa.Integer(), nullable=True),
        sa.Column("total_lecture_hours", sa.Integer(), nullable=True),
        sa.Column("total_practice_hours", sa.Integer(), nullable=True),
        sa.Column("total_lab_hours", sa.Integer(), nullable=True),
        sa.Column("total_self_study_hours", sa.Integer(), nullable=True),
        sa.Column("audited_hours", sa.Integer(), nullable=True),
        sa.Column("audited_hours_semester", sa.Integer(), nullable=True),
        sa.Column("semester_weeks", sa.Integer(), nullable=True),
        sa.Column("assessment_type", sa.String(length=120), nullable=True),
        sa.Column("education_form", sa.String(length=80), nullable=True),
        sa.Column("duration_label", sa.String(length=100), nullable=True),
        sa.Column("qualification_label", sa.String(length=200), nullable=True),
        sa.Column("department_name", sa.Text(), nullable=True),
        sa.Column("faculty_name", sa.Text(), nullable=True),
        sa.Column("chair_name", sa.Text(), nullable=True),
        sa.Column("source_row", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_document_url", sa.Text(), nullable=True),
        sa.Column("study_plan_url", sa.Text(), nullable=True),
        sa.Column("download_url", sa.Text(), nullable=True),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            " AND ".join(
                f"({column} IS NULL OR {column} >= 0)"
                for column in (
                    "course_number",
                    "hours",
                    "lecture_hours",
                    "practice_hours",
                    "lab_hours",
                    "self_study_hours",
                    "total_hours",
                    "total_lecture_hours",
                    "total_practice_hours",
                    "total_lab_hours",
                    "total_self_study_hours",
                    "audited_hours",
                    "audited_hours_semester",
                    "semester_weeks",
                )
            ),
            name=op.f("ck_curriculum_items_nonnegative_hour_values"),
        ),
        sa.CheckConstraint(
            "credits IS NULL OR credits >= 0", name=op.f("ck_curriculum_items_nonnegative_credits")
        ),
        sa.CheckConstraint("ordinal >= 1", name=op.f("ck_curriculum_items_valid_ordinal")),
        sa.CheckConstraint(
            "semester IS NULL OR semester >= 1", name=op.f("ck_curriculum_items_valid_semester")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "study_plan_id"],
            ["study_plans.release_id", "study_plans.id"],
            name="fk_curriculum_items_study_plan_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_curriculum_items_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_items")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_curriculum_items_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_curriculum_items_release_id"),
        sa.UniqueConstraint(
            "release_id", "study_plan_id", "ordinal", name="uq_curriculum_items_plan_ordinal"
        ),
    )
    op.create_index(
        "ix_curriculum_items_release_plan_ordinal",
        "curriculum_items",
        ["release_id", "study_plan_id", "ordinal"],
        unique=False,
    )
    op.create_table(
        "offering_requirement_links",
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_set_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "relation_type IN ('offering_has_exam_requirement_for_direction', "
            "'offering_has_direction_exam_requirement')",
            name=op.f("ck_offering_requirement_links_valid_relation_type"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "offering_id"],
            ["program_offerings.release_id", "program_offerings.id"],
            name="fk_offering_requirement_links_offering_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "requirement_set_id"],
            ["admission_requirement_sets.release_id", "admission_requirement_sets.id"],
            name="fk_offering_requirement_links_set_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_offering_requirement_links_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offering_requirement_links")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_offering_requirement_links_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_offering_requirement_links_release_id"),
        sa.UniqueConstraint(
            "release_id", "offering_id", "requirement_set_id", name="uq_offering_requirement_pair"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    has_batch_or_release = bind.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM import_batches) OR EXISTS (SELECT 1 FROM data_releases)"
        )
    ).scalar_one()
    if has_batch_or_release:
        raise RuntimeError(
            "Refusing to downgrade while import batch or release data exists; "
            "take a backup and migrate forward."
        )

    op.drop_table("offering_requirement_links")
    op.drop_index("ix_curriculum_items_release_plan_ordinal", table_name="curriculum_items")
    op.drop_table("curriculum_items")
    op.drop_table("competition_pool_offerings")
    op.drop_index("ix_study_plans_release_program", table_name="study_plans")
    op.drop_table("study_plans")
    op.drop_index("ix_program_offerings_release_direction", table_name="program_offerings")
    op.drop_index("ix_program_offerings_release_campaign", table_name="program_offerings")
    op.drop_table("program_offerings")
    op.drop_table("educational_program_departments")
    op.drop_index("ix_catalog_courses_release_program", table_name="catalog_courses")
    op.drop_table("catalog_courses")
    op.drop_index(
        "uq_requirement_nodes_single_root",
        table_name="admission_requirement_nodes",
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.drop_index(
        "ix_requirement_nodes_release_set_parent", table_name="admission_requirement_nodes"
    )
    op.drop_table("admission_requirement_nodes")
    op.drop_index("ix_tuition_assertions_release_direction", table_name="tuition_assertions")
    op.drop_table("tuition_assertions")
    op.drop_index(
        "ix_achievement_policies_release_campaign", table_name="individual_achievement_policies"
    )
    op.drop_table("individual_achievement_policies")
    op.drop_index(
        "ix_historical_statistics_release_year", table_name="historical_admission_statistics"
    )
    op.drop_table("historical_admission_statistics")
    op.drop_index("ix_educational_programs_release_code", table_name="educational_programs")
    op.drop_table("educational_programs")
    op.drop_table("direction_departments")
    op.drop_index("ix_competition_pools_release_direction", table_name="competition_pools")
    op.drop_index("ix_competition_pools_release_campaign", table_name="competition_pools")
    op.drop_table("competition_pools")
    op.drop_index(
        "ix_campaign_calendar_events_release_campaign", table_name="campaign_calendar_events"
    )
    op.drop_table("campaign_calendar_events")
    op.drop_index("ix_admission_statistics_release_year", table_name="admission_statistics")
    op.drop_table("admission_statistics")
    op.drop_index("ix_requirement_sets_release_campaign", table_name="admission_requirement_sets")
    op.drop_table("admission_requirement_sets")
    op.drop_index("ix_source_relationships_release_type", table_name="source_relationships")
    op.drop_table("source_relationships")
    op.drop_index("ix_source_observations_release_dataset", table_name="source_observations")
    op.drop_table("source_observations")
    op.drop_index("ix_manual_review_items_release_status", table_name="manual_review_items")
    op.drop_table("manual_review_items")
    op.drop_index("ix_directions_release_code", table_name="directions")
    op.drop_table("directions")
    op.drop_index("ix_departments_release_code", table_name="departments")
    op.drop_table("departments")
    op.drop_index(
        "ix_admission_document_pages_release_document", table_name="admission_document_pages"
    )
    op.drop_table("admission_document_pages")
    op.drop_index("ix_admission_campaigns_release_year", table_name="admission_campaigns")
    op.drop_table("admission_campaigns")
    op.drop_table("universities")
    op.drop_index("ix_source_artifacts_release_storage_status", table_name="source_artifacts")
    op.drop_table("source_artifacts")
    op.drop_table("quota_types")
    op.drop_table("funding_types")
    op.drop_index(
        "ix_admission_result_sources_release_stored", table_name="admission_result_sources"
    )
    op.drop_table("admission_result_sources")
    op.drop_table("admission_exams")
    op.drop_index("ix_admission_documents_release_scope", table_name="admission_documents")
    op.drop_table("admission_documents")
    # ### end Alembic commands ###
