"""add temporal facts and typed evidence

Revision ID: a0337fe46f54
Revises: e0784a907d45
Create Date: 2026-10-03 01:19:46.044991
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a0337fe46f54"
down_revision: str | None = "e0784a907d45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule_packs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_packs")),
        sa.UniqueConstraint("external_key", name=op.f("uq_rule_packs_external_key")),
    )
    op.create_table(
        "rule_scopes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope_key", sa.String(length=512), nullable=False),
        sa.Column("university_key", sa.String(length=256), nullable=True),
        sa.Column("campaign_year", sa.Integer(), nullable=True),
        sa.Column("education_level_code", sa.String(length=80), nullable=True),
        sa.Column("audience_code", sa.String(length=80), nullable=True),
        sa.Column("surface_code", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "campaign_year IS NULL OR campaign_year BETWEEN 1900 AND 2200",
            name=op.f("ck_rule_scopes_valid_campaign_year"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_scopes")),
        sa.UniqueConstraint("scope_key", name=op.f("uq_rule_scopes_scope_key")),
        sa.UniqueConstraint(
            "university_key",
            "campaign_year",
            "education_level_code",
            "audience_code",
            "surface_code",
            name="uq_rule_scopes_exact_axes",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "rule_pack_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_pack_id", sa.Uuid(), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("valid_during", postgresql.DATERANGE(), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("scope_id"), "="),
            (sa.column("valid_during"), "&&"),
            where=sa.text("status = 'published'"),
            using="gist",
            name="ex_rule_pack_versions_published_scope_period",
        ),
        sa.CheckConstraint(
            "checksum ~ '^[0-9a-f]{64}$'", name=op.f("ck_rule_pack_versions_valid_checksum")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'retired')",
            name=op.f("ck_rule_pack_versions_valid_status"),
        ),
        sa.CheckConstraint(
            "NOT isempty(valid_during) AND NOT lower_inf(valid_during)",
            name=op.f("ck_rule_pack_versions_nonempty_validity_range"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_rule_pack_versions_valid_version")),
        sa.ForeignKeyConstraint(
            ["rule_pack_id"], ["rule_packs.id"], name="fk_rule_versions_pack", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"], ["rule_scopes.id"], name="fk_rule_versions_scope", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_pack_versions")),
        sa.UniqueConstraint(
            "rule_pack_id", "scope_id", "version", name="uq_rule_pack_versions_pack_scope_version"
        ),
    )
    op.create_index(
        "ix_rule_pack_versions_scope_status",
        "rule_pack_versions",
        ["scope_id", "status"],
        unique=False,
    )
    op.create_table(
        "source_evidence",
        sa.Column("source_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("field_path", sa.String(length=512), nullable=False),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quoted_fragment", sa.Text(), nullable=True),
        sa.Column("claim", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.CheckConstraint(
            "verification_status IN ('source_backed', 'unverified', 'manual_review')",
            name=op.f("ck_source_evidence_valid_verification_status"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "source_artifact_id"],
            ["source_artifacts.release_id", "source_artifacts.id"],
            name="fk_source_evidence_artifact_release",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_source_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_evidence")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_source_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_source_evidence_release_id"),
    )
    op.create_index(
        "ix_source_evidence_release_artifact",
        "source_evidence",
        ["release_id", "source_artifact_id"],
        unique=False,
    )
    op.create_check_constraint(
        op.f("ck_source_evidence_nonempty_field_path"),
        "source_evidence",
        "length(field_path) > 0",
    )
    op.create_table(
        "admission_document_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "document_id"],
            ["admission_documents.release_id", "admission_documents.id"],
            name="fk_admission_document_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_admission_document_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_document_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_document_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "document_id",
            name="uq_admission_document_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_admission_document_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_document_evidence_release_id"),
    )
    op.create_index(
        "ix_admission_document_evidence_release_target",
        "admission_document_evidence",
        ["release_id", "document_id"],
        unique=False,
    )
    op.create_table(
        "admission_document_page_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_admission_document_page_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "page_id"],
            ["admission_document_pages.release_id", "admission_document_pages.id"],
            name="fk_admission_document_page_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_document_page_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_document_page_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "page_id",
            name="uq_admission_document_page_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_admission_document_page_evidence_release_external_key",
        ),
        sa.UniqueConstraint(
            "release_id", "id", name="uq_admission_document_page_evidence_release_id"
        ),
    )
    op.create_index(
        "ix_admission_document_page_evidence_release_target",
        "admission_document_page_evidence",
        ["release_id", "page_id"],
        unique=False,
    )
    op.create_table(
        "admission_result_source_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("result_source_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_admission_result_source_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "result_source_id"],
            ["admission_result_sources.release_id", "admission_result_sources.id"],
            name="fk_admission_result_source_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_result_source_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_result_source_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "result_source_id",
            name="uq_admission_result_source_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_admission_result_source_evidence_release_external_key",
        ),
        sa.UniqueConstraint(
            "release_id", "id", name="uq_admission_result_source_evidence_release_id"
        ),
    )
    op.create_index(
        "ix_admission_result_source_evidence_release_target",
        "admission_result_source_evidence",
        ["release_id", "result_source_id"],
        unique=False,
    )
    op.create_table(
        "campaign_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "campaign_id"],
            ["admission_campaigns.release_id", "admission_campaigns.id"],
            name="fk_campaign_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_campaign_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_campaign_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_evidence")),
        sa.UniqueConstraint(
            "release_id", "evidence_id", "campaign_id", name="uq_campaign_evidence_evidence_target"
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_campaign_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_campaign_evidence_release_id"),
    )
    op.create_index(
        "ix_campaign_evidence_release_target",
        "campaign_evidence",
        ["release_id", "campaign_id"],
        unique=False,
    )
    op.create_table(
        "department_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "department_id"],
            ["departments.release_id", "departments.id"],
            name="fk_department_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_department_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_department_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "department_id",
            name="uq_department_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_department_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_department_evidence_release_id"),
    )
    op.create_index(
        "ix_department_evidence_release_target",
        "department_evidence",
        ["release_id", "department_id"],
        unique=False,
    )
    op.create_table(
        "direction_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_id"],
            ["directions.release_id", "directions.id"],
            name="fk_direction_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_direction_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_direction_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_direction_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "direction_id",
            name="uq_direction_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_direction_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_direction_evidence_release_id"),
    )
    op.create_index(
        "ix_direction_evidence_release_target",
        "direction_evidence",
        ["release_id", "direction_id"],
        unique=False,
    )
    op.create_table(
        "manual_review_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("manual_review_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_manual_review_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "manual_review_id"],
            ["manual_review_items.release_id", "manual_review_items.id"],
            name="fk_manual_review_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_manual_review_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_review_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "manual_review_id",
            name="uq_manual_review_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_manual_review_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_manual_review_evidence_release_id"),
    )
    op.create_index(
        "ix_manual_review_evidence_release_target",
        "manual_review_evidence",
        ["release_id", "manual_review_id"],
        unique=False,
    )
    op.create_table(
        "source_relationship_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_source_relationship_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "relationship_id"],
            ["source_relationships.release_id", "source_relationships.id"],
            name="fk_source_relationship_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_source_relationship_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_relationship_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "relationship_id",
            name="uq_source_relationship_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_source_relationship_evidence_release_external_key",
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_source_relationship_evidence_release_id"),
    )
    op.create_index(
        "ix_source_relationship_evidence_release_target",
        "source_relationship_evidence",
        ["release_id", "relationship_id"],
        unique=False,
    )
    op.create_table(
        "university_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_university_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "university_id"],
            ["universities.release_id", "universities.id"],
            name="fk_university_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_university_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_university_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "university_id",
            name="uq_university_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_university_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_university_evidence_release_id"),
    )
    op.create_index(
        "ix_university_evidence_release_target",
        "university_evidence",
        ["release_id", "university_id"],
        unique=False,
    )
    op.create_table(
        "achievement_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("achievement_policy_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "achievement_policy_id"],
            ["individual_achievement_policies.release_id", "individual_achievement_policies.id"],
            name="fk_achievement_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_achievement_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_achievement_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievement_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "achievement_policy_id",
            name="uq_achievement_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_achievement_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_achievement_evidence_release_id"),
    )
    op.create_index(
        "ix_achievement_evidence_release_target",
        "achievement_evidence",
        ["release_id", "achievement_policy_id"],
        unique=False,
    )
    op.create_table(
        "admission_statistic_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("statistic_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_admission_statistic_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "statistic_id"],
            ["admission_statistics.release_id", "admission_statistics.id"],
            name="fk_admission_statistic_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_admission_statistic_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_statistic_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "statistic_id",
            name="uq_admission_statistic_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_admission_statistic_evidence_release_external_key",
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_admission_statistic_evidence_release_id"),
    )
    op.create_index(
        "ix_admission_statistic_evidence_release_target",
        "admission_statistic_evidence",
        ["release_id", "statistic_id"],
        unique=False,
    )
    op.create_table(
        "calendar_event_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "calendar_event_id"],
            ["campaign_calendar_events.release_id", "campaign_calendar_events.id"],
            name="fk_calendar_event_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_calendar_event_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_calendar_event_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_event_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "calendar_event_id",
            name="uq_calendar_event_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_calendar_event_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_calendar_event_evidence_release_id"),
    )
    op.create_index(
        "ix_calendar_event_evidence_release_target",
        "calendar_event_evidence",
        ["release_id", "calendar_event_id"],
        unique=False,
    )
    op.create_table(
        "competition_pool_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("pool_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_competition_pool_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "pool_id"],
            ["competition_pools.release_id", "competition_pools.id"],
            name="fk_competition_pool_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_competition_pool_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_pool_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "pool_id",
            name="uq_competition_pool_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_competition_pool_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_competition_pool_evidence_release_id"),
    )
    op.create_index(
        "ix_competition_pool_evidence_release_target",
        "competition_pool_evidence",
        ["release_id", "pool_id"],
        unique=False,
    )
    op.create_table(
        "direction_department_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("direction_department_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "direction_department_id"],
            ["direction_departments.release_id", "direction_departments.id"],
            name="fk_direction_department_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_direction_department_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_direction_department_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_direction_department_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "direction_department_id",
            name="uq_direction_department_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_direction_department_evidence_release_external_key",
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_direction_department_evidence_release_id"),
    )
    op.create_index(
        "ix_direction_department_evidence_release_target",
        "direction_department_evidence",
        ["release_id", "direction_department_id"],
        unique=False,
    )
    op.create_table(
        "historical_statistic_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("statistic_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_historical_statistic_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "statistic_id"],
            ["historical_admission_statistics.release_id", "historical_admission_statistics.id"],
            name="fk_historical_statistic_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_historical_statistic_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_statistic_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "statistic_id",
            name="uq_historical_statistic_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_historical_statistic_evidence_release_external_key",
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_historical_statistic_evidence_release_id"),
    )
    op.create_index(
        "ix_historical_statistic_evidence_release_target",
        "historical_statistic_evidence",
        ["release_id", "statistic_id"],
        unique=False,
    )
    op.create_table(
        "place_quota_assertions",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("pool_id", sa.Uuid(), nullable=True),
        sa.Column("funding_type_id", sa.Uuid(), nullable=True),
        sa.Column("quota_type_id", sa.Uuid(), nullable=True),
        sa.Column("places", sa.Integer(), nullable=False),
        sa.Column("scope_level", sa.String(length=80), nullable=True),
        sa.Column("source_locators", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "places >= 0", name=op.f("ck_place_quota_assertions_nonnegative_places")
        ),
        sa.CheckConstraint(
            "valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to",
            name=op.f("ck_place_quota_assertions_valid_validity_period"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "campaign_id"],
            ["admission_campaigns.release_id", "admission_campaigns.id"],
            name="fk_place_quota_assertions_campaign_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "funding_type_id"],
            ["funding_types.release_id", "funding_types.id"],
            name="fk_place_quota_assertions_funding_type_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "pool_id"],
            ["competition_pools.release_id", "competition_pools.id"],
            name="fk_place_quota_assertions_pool_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "quota_type_id"],
            ["quota_types.release_id", "quota_types.id"],
            name="fk_place_quota_assertions_quota_type_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_place_quota_assertions_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_quota_assertions")),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_place_quota_assertions_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_place_quota_assertions_release_id"),
    )
    op.create_index(
        "ix_place_quota_assertions_release_campaign",
        "place_quota_assertions",
        ["release_id", "campaign_id"],
        unique=False,
    )
    op.create_index(
        "ix_place_quota_assertions_release_pool",
        "place_quota_assertions",
        ["release_id", "pool_id"],
        unique=False,
    )
    op.create_table(
        "program_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_program_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "program_id"],
            ["educational_programs.release_id", "educational_programs.id"],
            name="fk_program_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_program_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_evidence")),
        sa.UniqueConstraint(
            "release_id", "evidence_id", "program_id", name="uq_program_evidence_evidence_target"
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_program_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_program_evidence_release_id"),
    )
    op.create_index(
        "ix_program_evidence_release_target",
        "program_evidence",
        ["release_id", "program_id"],
        unique=False,
    )
    op.create_table(
        "requirement_set_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_set_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_requirement_set_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "requirement_set_id"],
            ["admission_requirement_sets.release_id", "admission_requirement_sets.id"],
            name="fk_requirement_set_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_requirement_set_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_set_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "requirement_set_id",
            name="uq_requirement_set_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_requirement_set_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_requirement_set_evidence_release_id"),
    )
    op.create_index(
        "ix_requirement_set_evidence_release_target",
        "requirement_set_evidence",
        ["release_id", "requirement_set_id"],
        unique=False,
    )
    op.create_table(
        "tuition_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("tuition_assertion_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_tuition_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "tuition_assertion_id"],
            ["tuition_assertions.release_id", "tuition_assertions.id"],
            name="fk_tuition_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_tuition_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tuition_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "tuition_assertion_id",
            name="uq_tuition_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_tuition_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_tuition_evidence_release_id"),
    )
    op.create_index(
        "ix_tuition_evidence_release_target",
        "tuition_evidence",
        ["release_id", "tuition_assertion_id"],
        unique=False,
    )
    op.create_table(
        "catalog_course_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "course_id"],
            ["catalog_courses.release_id", "catalog_courses.id"],
            name="fk_catalog_course_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_catalog_course_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_catalog_course_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_course_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "course_id",
            name="uq_catalog_course_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_catalog_course_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_catalog_course_evidence_release_id"),
    )
    op.create_index(
        "ix_catalog_course_evidence_release_target",
        "catalog_course_evidence",
        ["release_id", "course_id"],
        unique=False,
    )
    op.create_table(
        "offering_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("offering_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_offering_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "offering_id"],
            ["program_offerings.release_id", "program_offerings.id"],
            name="fk_offering_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_offering_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offering_evidence")),
        sa.UniqueConstraint(
            "release_id", "evidence_id", "offering_id", name="uq_offering_evidence_evidence_target"
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_offering_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_offering_evidence_release_id"),
    )
    op.create_index(
        "ix_offering_evidence_release_target",
        "offering_evidence",
        ["release_id", "offering_id"],
        unique=False,
    )
    op.create_table(
        "place_quota_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("assertion_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "assertion_id"],
            ["place_quota_assertions.release_id", "place_quota_assertions.id"],
            name="fk_place_quota_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_place_quota_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_place_quota_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_quota_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "assertion_id",
            name="uq_place_quota_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_place_quota_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_place_quota_evidence_release_id"),
    )
    op.create_index(
        "ix_place_quota_evidence_release_target",
        "place_quota_evidence",
        ["release_id", "assertion_id"],
        unique=False,
    )
    op.create_table(
        "program_department_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("program_department_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_program_department_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "program_department_id"],
            ["educational_program_departments.release_id", "educational_program_departments.id"],
            name="fk_program_department_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_program_department_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_department_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "program_department_id",
            name="uq_program_department_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_program_department_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_program_department_evidence_release_id"),
    )
    op.create_index(
        "ix_program_department_evidence_release_target",
        "program_department_evidence",
        ["release_id", "program_department_id"],
        unique=False,
    )
    op.create_table(
        "requirement_node_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_node_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_requirement_node_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "requirement_node_id"],
            ["admission_requirement_nodes.release_id", "admission_requirement_nodes.id"],
            name="fk_requirement_node_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_requirement_node_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_node_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "requirement_node_id",
            name="uq_requirement_node_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_requirement_node_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_requirement_node_evidence_release_id"),
    )
    op.create_index(
        "ix_requirement_node_evidence_release_target",
        "requirement_node_evidence",
        ["release_id", "requirement_node_id"],
        unique=False,
    )
    op.create_table(
        "study_plan_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("study_plan_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_study_plan_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "study_plan_id"],
            ["study_plans.release_id", "study_plans.id"],
            name="fk_study_plan_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_study_plan_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_plan_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "study_plan_id",
            name="uq_study_plan_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_study_plan_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_study_plan_evidence_release_id"),
    )
    op.create_index(
        "ix_study_plan_evidence_release_target",
        "study_plan_evidence",
        ["release_id", "study_plan_id"],
        unique=False,
    )
    op.create_table(
        "curriculum_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_item_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "curriculum_item_id"],
            ["curriculum_items.release_id", "curriculum_items.id"],
            name="fk_curriculum_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_curriculum_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_curriculum_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "curriculum_item_id",
            name="uq_curriculum_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_curriculum_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_curriculum_evidence_release_id"),
    )
    op.create_index(
        "ix_curriculum_evidence_release_target",
        "curriculum_evidence",
        ["release_id", "curriculum_item_id"],
        unique=False,
    )
    op.create_table(
        "offering_requirement_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("link_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_offering_requirement_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "link_id"],
            ["offering_requirement_links.release_id", "offering_requirement_links.id"],
            name="fk_offering_requirement_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_offering_requirement_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offering_requirement_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "link_id",
            name="uq_offering_requirement_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id",
            "external_key",
            name="uq_offering_requirement_evidence_release_external_key",
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_offering_requirement_evidence_release_id"),
    )
    op.create_index(
        "ix_offering_requirement_evidence_release_target",
        "offering_requirement_evidence",
        ["release_id", "link_id"],
        unique=False,
    )
    op.create_table(
        "pool_offering_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("pool_offering_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "evidence_id"],
            ["source_evidence.release_id", "source_evidence.id"],
            name="fk_pool_offering_evidence_evidence_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "pool_offering_id"],
            ["competition_pool_offerings.release_id", "competition_pool_offerings.id"],
            name="fk_pool_offering_evidence_target_release",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["data_releases.id"],
            name=op.f("fk_pool_offering_evidence_release_id_data_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pool_offering_evidence")),
        sa.UniqueConstraint(
            "release_id",
            "evidence_id",
            "pool_offering_id",
            name="uq_pool_offering_evidence_evidence_target",
        ),
        sa.UniqueConstraint(
            "release_id", "external_key", name="uq_pool_offering_evidence_release_external_key"
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_pool_offering_evidence_release_id"),
    )
    op.create_index(
        "ix_pool_offering_evidence_release_target",
        "pool_offering_evidence",
        ["release_id", "pool_offering_id"],
        unique=False,
    )
    op.add_column("admission_requirement_sets", sa.Column("valid_from", sa.Date(), nullable=True))
    op.add_column("admission_requirement_sets", sa.Column("valid_to", sa.Date(), nullable=True))
    op.add_column(
        "admission_requirement_sets",
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "admission_requirement_sets",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("admission_statistics", sa.Column("valid_from", sa.Date(), nullable=True))
    op.add_column("admission_statistics", sa.Column("valid_to", sa.Date(), nullable=True))
    op.add_column(
        "admission_statistics", sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "admission_statistics",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("competition_pools", sa.Column("valid_from", sa.Date(), nullable=True))
    op.add_column("competition_pools", sa.Column("valid_to", sa.Date(), nullable=True))
    op.add_column(
        "competition_pools", sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "competition_pools",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "historical_admission_statistics", sa.Column("valid_from", sa.Date(), nullable=True)
    )
    op.add_column(
        "historical_admission_statistics", sa.Column("valid_to", sa.Date(), nullable=True)
    )
    op.add_column(
        "historical_admission_statistics",
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "historical_admission_statistics",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "individual_achievement_policies", sa.Column("valid_from", sa.Date(), nullable=True)
    )
    op.add_column(
        "individual_achievement_policies", sa.Column("valid_to", sa.Date(), nullable=True)
    )
    op.add_column(
        "individual_achievement_policies",
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "individual_achievement_policies",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("tuition_assertions", sa.Column("valid_from", sa.Date(), nullable=True))
    op.add_column("tuition_assertions", sa.Column("valid_to", sa.Date(), nullable=True))
    op.add_column(
        "tuition_assertions", sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "tuition_assertions",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    for table_name in (
        "admission_requirement_sets",
        "admission_statistics",
        "competition_pools",
        "historical_admission_statistics",
        "individual_achievement_policies",
        "tuition_assertions",
    ):
        op.create_check_constraint(
            op.f(f"ck_{table_name}_valid_validity_period"),
            table_name,
            "valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to",
        )

    op.execute(
        """
        CREATE FUNCTION academic_data_guard_committed_fact()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            target_release_id uuid;
        BEGIN
            IF TG_OP = 'INSERT' THEN
                target_release_id := NEW.release_id;
            ELSIF TG_OP = 'DELETE' THEN
                target_release_id := OLD.release_id;
            ELSE
                target_release_id := OLD.release_id;
                IF NEW.release_id <> OLD.release_id THEN
                    RAISE EXCEPTION 'facts cannot move between data releases'
                        USING ERRCODE = '55000';
                END IF;
            END IF;

            IF EXISTS (
                SELECT 1 FROM data_releases
                WHERE id = target_release_id AND status = 'committed'
            ) THEN
                RAISE EXCEPTION 'committed release facts are append-only'
                    USING ERRCODE = '55000';
            END IF;

            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    for table_name in (
        "admission_requirement_sets",
        "admission_statistics",
        "competition_pools",
        "historical_admission_statistics",
        "individual_achievement_policies",
        "place_quota_assertions",
        "tuition_assertions",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_committed_immutable "
            f"BEFORE INSERT OR UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION academic_data_guard_committed_fact()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    has_imported_or_policy_data = bind.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM import_batches) "
            "OR EXISTS (SELECT 1 FROM data_releases) "
            "OR EXISTS (SELECT 1 FROM rule_pack_versions)"
        )
    ).scalar_one()
    if has_imported_or_policy_data:
        raise RuntimeError(
            "Refusing to downgrade while import batch or release data exists; "
            "take a backup and migrate forward."
        )

    for table_name in (
        "admission_requirement_sets",
        "admission_statistics",
        "competition_pools",
        "historical_admission_statistics",
        "individual_achievement_policies",
        "place_quota_assertions",
        "tuition_assertions",
    ):
        op.execute(f"DROP TRIGGER trg_{table_name}_committed_immutable ON {table_name}")
    op.execute("DROP FUNCTION academic_data_guard_committed_fact()")

    for table_name in (
        "admission_requirement_sets",
        "admission_statistics",
        "competition_pools",
        "historical_admission_statistics",
        "individual_achievement_policies",
        "tuition_assertions",
    ):
        op.drop_constraint(
            op.f(f"ck_{table_name}_valid_validity_period"), table_name, type_="check"
        )

    op.drop_column("tuition_assertions", "ingested_at")
    op.drop_column("tuition_assertions", "observed_at")
    op.drop_column("tuition_assertions", "valid_to")
    op.drop_column("tuition_assertions", "valid_from")
    op.drop_column("individual_achievement_policies", "ingested_at")
    op.drop_column("individual_achievement_policies", "observed_at")
    op.drop_column("individual_achievement_policies", "valid_to")
    op.drop_column("individual_achievement_policies", "valid_from")
    op.drop_column("historical_admission_statistics", "ingested_at")
    op.drop_column("historical_admission_statistics", "observed_at")
    op.drop_column("historical_admission_statistics", "valid_to")
    op.drop_column("historical_admission_statistics", "valid_from")
    op.drop_column("competition_pools", "ingested_at")
    op.drop_column("competition_pools", "observed_at")
    op.drop_column("competition_pools", "valid_to")
    op.drop_column("competition_pools", "valid_from")
    op.drop_column("admission_statistics", "ingested_at")
    op.drop_column("admission_statistics", "observed_at")
    op.drop_column("admission_statistics", "valid_to")
    op.drop_column("admission_statistics", "valid_from")
    op.drop_column("admission_requirement_sets", "ingested_at")
    op.drop_column("admission_requirement_sets", "observed_at")
    op.drop_column("admission_requirement_sets", "valid_to")
    op.drop_column("admission_requirement_sets", "valid_from")
    op.drop_index("ix_pool_offering_evidence_release_target", table_name="pool_offering_evidence")
    op.drop_table("pool_offering_evidence")
    op.drop_index(
        "ix_offering_requirement_evidence_release_target",
        table_name="offering_requirement_evidence",
    )
    op.drop_table("offering_requirement_evidence")
    op.drop_index("ix_curriculum_evidence_release_target", table_name="curriculum_evidence")
    op.drop_table("curriculum_evidence")
    op.drop_index("ix_study_plan_evidence_release_target", table_name="study_plan_evidence")
    op.drop_table("study_plan_evidence")
    op.drop_index(
        "ix_requirement_node_evidence_release_target", table_name="requirement_node_evidence"
    )
    op.drop_table("requirement_node_evidence")
    op.drop_index(
        "ix_program_department_evidence_release_target", table_name="program_department_evidence"
    )
    op.drop_table("program_department_evidence")
    op.drop_index("ix_place_quota_evidence_release_target", table_name="place_quota_evidence")
    op.drop_table("place_quota_evidence")
    op.drop_index("ix_offering_evidence_release_target", table_name="offering_evidence")
    op.drop_table("offering_evidence")
    op.drop_index("ix_catalog_course_evidence_release_target", table_name="catalog_course_evidence")
    op.drop_table("catalog_course_evidence")
    op.drop_index("ix_tuition_evidence_release_target", table_name="tuition_evidence")
    op.drop_table("tuition_evidence")
    op.drop_index(
        "ix_requirement_set_evidence_release_target", table_name="requirement_set_evidence"
    )
    op.drop_table("requirement_set_evidence")
    op.drop_index("ix_program_evidence_release_target", table_name="program_evidence")
    op.drop_table("program_evidence")
    op.drop_index("ix_place_quota_assertions_release_pool", table_name="place_quota_assertions")
    op.drop_index("ix_place_quota_assertions_release_campaign", table_name="place_quota_assertions")
    op.drop_table("place_quota_assertions")
    op.drop_index(
        "ix_historical_statistic_evidence_release_target",
        table_name="historical_statistic_evidence",
    )
    op.drop_table("historical_statistic_evidence")
    op.drop_index(
        "ix_direction_department_evidence_release_target",
        table_name="direction_department_evidence",
    )
    op.drop_table("direction_department_evidence")
    op.drop_index(
        "ix_competition_pool_evidence_release_target", table_name="competition_pool_evidence"
    )
    op.drop_table("competition_pool_evidence")
    op.drop_index("ix_calendar_event_evidence_release_target", table_name="calendar_event_evidence")
    op.drop_table("calendar_event_evidence")
    op.drop_index(
        "ix_admission_statistic_evidence_release_target", table_name="admission_statistic_evidence"
    )
    op.drop_table("admission_statistic_evidence")
    op.drop_index("ix_achievement_evidence_release_target", table_name="achievement_evidence")
    op.drop_table("achievement_evidence")
    op.drop_index("ix_university_evidence_release_target", table_name="university_evidence")
    op.drop_table("university_evidence")
    op.drop_index(
        "ix_source_relationship_evidence_release_target", table_name="source_relationship_evidence"
    )
    op.drop_table("source_relationship_evidence")
    op.drop_index("ix_manual_review_evidence_release_target", table_name="manual_review_evidence")
    op.drop_table("manual_review_evidence")
    op.drop_index("ix_direction_evidence_release_target", table_name="direction_evidence")
    op.drop_table("direction_evidence")
    op.drop_index("ix_department_evidence_release_target", table_name="department_evidence")
    op.drop_table("department_evidence")
    op.drop_index("ix_campaign_evidence_release_target", table_name="campaign_evidence")
    op.drop_table("campaign_evidence")
    op.drop_index(
        "ix_admission_result_source_evidence_release_target",
        table_name="admission_result_source_evidence",
    )
    op.drop_table("admission_result_source_evidence")
    op.drop_index(
        "ix_admission_document_page_evidence_release_target",
        table_name="admission_document_page_evidence",
    )
    op.drop_table("admission_document_page_evidence")
    op.drop_index(
        "ix_admission_document_evidence_release_target", table_name="admission_document_evidence"
    )
    op.drop_table("admission_document_evidence")
    op.drop_index("ix_source_evidence_release_artifact", table_name="source_evidence")
    op.drop_table("source_evidence")
    op.drop_index("ix_rule_pack_versions_scope_status", table_name="rule_pack_versions")
    op.drop_table("rule_pack_versions")
    op.drop_table("rule_scopes")
    op.drop_table("rule_packs")
    # ### end Alembic commands ###
